services:
  fl-server:
    build: .
    image: fl-simulation-img
    container_name: fl_server
    volumes:
    - ./etc:/app/etc
    command: python app-server.py --host 0.0.0.0 --required_clients 25 --clients_per_round
      5 --max_rounds 3
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities:
            - gpu
    ports:
    - 65432:65432
    environment:
    - NVIDIA_VISIBLE_DEVICES=all
    - PYTORCH_ALLOC_CONF=expandable_segments:True
    - MALLOC_ARENA_MAX=2
    - OMP_NUM_THREADS=1
    ipc: host
    networks:
    - fl-network
  client_8156:
    image: fl-simulation-img
    runtime: nvidia
    container_name: fl_client_8156
    volumes:
    - ./etc:/app/etc
    depends_on:
      fl-server:
        condition: service_started
    command: python app-client.py --mongo_uri "mongodb://fl_mongo:27017/" --loc="austin"
      --data_path "dataset/pecanstreet/15min/austin/train/" --test_path "dataset/pecanstreet/15min/austin/test/"  --host
      fl-server --filter_bs 8156 --epochs 15 --batch_size 128 --num_workers 0
    environment:
    - NVIDIA_VISIBLE_DEVICES=all
    - CUBLAS_WORKSPACE_CONFIG=:4096:8
    - PYTORCH_ALLOC_CONF=expandable_segments:True
    - MALLOC_ARENA_MAX=2
    - OMP_NUM_THREADS=1
    - GPU_FRACTION=0.03
    - CLIENT_ID=8156
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities:
            - gpu
    ipc: host
    networks:
    - fl-network
  client_2335:
    image: fl-simulation-img
    runtime: nvidia
    container_name: fl_client_2335
    volumes:
    - ./etc:/app/etc
    depends_on:
      fl-server:
        condition: service_started
    command: python app-client.py --mongo_uri "mongodb://fl_mongo:27017/" --loc="austin"
      --data_path "dataset/pecanstreet/15min/austin/train/" --test_path "dataset/pecanstreet/15min/austin/test/"  --host
      fl-server --filter_bs 2335 --epochs 15 --batch_size 128 --num_workers 0
    environment:
    - NVIDIA_VISIBLE_DEVICES=all
    - CUBLAS_WORKSPACE_CONFIG=:4096:8
    - PYTORCH_ALLOC_CONF=expandable_segments:True
    - MALLOC_ARENA_MAX=2
    - OMP_NUM_THREADS=1
    - GPU_FRACTION=0.03
    - CLIENT_ID=2335
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities:
            - gpu
    ipc: host
    networks:
    - fl-network
  client_9922:
    image: fl-simulation-img
    runtime: nvidia
    container_name: fl_client_9922
    volumes:
    - ./etc:/app/etc
    depends_on:
      fl-server:
        condition: service_started
    command: python app-client.py --mongo_uri "mongodb://fl_mongo:27017/" --loc="austin"
      --data_path "dataset/pecanstreet/15min/austin/train/" --test_path "dataset/pecanstreet/15min/austin/test/"  --host
      fl-server --filter_bs 9922 --epochs 15 --batch_size 128 --num_workers 0
    environment:
    - NVIDIA_VISIBLE_DEVICES=all
    - CUBLAS_WORKSPACE_CONFIG=:4096:8
    - PYTORCH_ALLOC_CONF=expandable_segments:True
    - MALLOC_ARENA_MAX=2
    - OMP_NUM_THREADS=1
    - GPU_FRACTION=0.03
    - CLIENT_ID=9922
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities:
            - gpu
    ipc: host
    networks:
    - fl-network
  client_3039:
    image: fl-simulation-img
    runtime: nvidia
    container_name: fl_client_3039
    volumes:
    - ./etc:/app/etc
    depends_on:
      fl-server:
        condition: service_started
    command: python app-client.py --mongo_uri "mongodb://fl_mongo:27017/" --loc="austin"
      --data_path "dataset/pecanstreet/15min/austin/train/" --test_path "dataset/pecanstreet/15min/austin/test/"  --host
      fl-server --filter_bs 3039 --epochs 15 --batch_size 128 --num_workers 0
    environment:
    - NVIDIA_VISIBLE_DEVICES=all
    - CUBLAS_WORKSPACE_CONFIG=:4096:8
    - PYTORCH_ALLOC_CONF=expandable_segments:True
    - MALLOC_ARENA_MAX=2
    - OMP_NUM_THREADS=1
    - GPU_FRACTION=0.03
    - CLIENT_ID=3039
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities:
            - gpu
    ipc: host
    networks:
    - fl-network
  client_4031:
    image: fl-simulation-img
    runtime: nvidia
    container_name: fl_client_4031
    volumes:
    - ./etc:/app/etc
    depends_on:
      fl-server:
        condition: service_started
    command: python app-client.py --mongo_uri "mongodb://fl_mongo:27017/" --loc="austin"
      --data_path "dataset/pecanstreet/15min/austin/train/" --test_path "dataset/pecanstreet/15min/austin/test/"  --host
      fl-server --filter_bs 4031 --epochs 15 --batch_size 128 --num_workers 0
    environment:
    - NVIDIA_VISIBLE_DEVICES=all
    - CUBLAS_WORKSPACE_CONFIG=:4096:8
    - PYTORCH_ALLOC_CONF=expandable_segments:True
    - MALLOC_ARENA_MAX=2
    - OMP_NUM_THREADS=1
    - GPU_FRACTION=0.03
    - CLIENT_ID=4031
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities:
            - gpu
    ipc: host
    networks:
    - fl-network
  client_8386:
    image: fl-simulation-img
    runtime: nvidia
    container_name: fl_client_8386
    volumes:
    - ./etc:/app/etc
    depends_on:
      fl-server:
        condition: service_started
    command: python app-client.py --mongo_uri "mongodb://fl_mongo:27017/" --loc="austin"
      --data_path "dataset/pecanstreet/15min/austin/train/" --test_path "dataset/pecanstreet/15min/austin/test/"  --host
      fl-server --filter_bs 8386 --epochs 15 --batch_size 128 --num_workers 0
    environment:
    - NVIDIA_VISIBLE_DEVICES=all
    - CUBLAS_WORKSPACE_CONFIG=:4096:8
    - PYTORCH_ALLOC_CONF=expandable_segments:True
    - MALLOC_ARENA_MAX=2
    - OMP_NUM_THREADS=1
    - GPU_FRACTION=0.03
    - CLIENT_ID=8386
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities:
            - gpu
    ipc: host
    networks:
    - fl-network
  client_7951:
    image: fl-simulation-img
    runtime: nvidia
    container_name: fl_client_7951
    volumes:
    - ./etc:/app/etc
    depends_on:
      fl-server:
        condition: service_started
    command: python app-client.py --mongo_uri "mongodb://fl_mongo:27017/" --loc="austin"
      --data_path "dataset/pecanstreet/15min/austin/train/" --test_path "dataset/pecanstreet/15min/austin/test/"  --host
      fl-server --filter_bs 7951 --epochs 15 --batch_size 128 --num_workers 0
    environment:
    - NVIDIA_VISIBLE_DEVICES=all
    - CUBLAS_WORKSPACE_CONFIG=:4096:8
    - PYTORCH_ALLOC_CONF=expandable_segments:True
    - MALLOC_ARENA_MAX=2
    - OMP_NUM_THREADS=1
    - GPU_FRACTION=0.03
    - CLIENT_ID=7951
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities:
            - gpu
    ipc: host
    networks:
    - fl-network
  client_3538:
    image: fl-simulation-img
    runtime: nvidia
    container_name: fl_client_3538
    volumes:
    - ./etc:/app/etc
    depends_on:
      fl-server:
        condition: service_started
    command: python app-client.py --mongo_uri "mongodb://fl_mongo:27017/" --loc="austin"
      --data_path "dataset/pecanstreet/15min/austin/train/" --test_path "dataset/pecanstreet/15min/austin/test/"  --host
      fl-server --filter_bs 3538 --epochs 15 --batch_size 128 --num_workers 0
    environment:
    - NVIDIA_VISIBLE_DEVICES=all
    - CUBLAS_WORKSPACE_CONFIG=:4096:8
    - PYTORCH_ALLOC_CONF=expandable_segments:True
    - MALLOC_ARENA_MAX=2
    - OMP_NUM_THREADS=1
    - GPU_FRACTION=0.03
    - CLIENT_ID=3538
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities:
            - gpu
    ipc: host
    networks:
    - fl-network
  client_9160:
    image: fl-simulation-img
    runtime: nvidia
    container_name: fl_client_9160
    volumes:
    - ./etc:/app/etc
    depends_on:
      fl-server:
        condition: service_started
    command: python app-client.py --mongo_uri "mongodb://fl_mongo:27017/" --loc="austin"
      --data_path "dataset/pecanstreet/15min/austin/train/" --test_path "dataset/pecanstreet/15min/austin/test/"  --host
      fl-server --filter_bs 9160 --epochs 15 --batch_size 128 --num_workers 0
    environment:
    - NVIDIA_VISIBLE_DEVICES=all
    - CUBLAS_WORKSPACE_CONFIG=:4096:8
    - PYTORCH_ALLOC_CONF=expandable_segments:True
    - MALLOC_ARENA_MAX=2
    - OMP_NUM_THREADS=1
    - GPU_FRACTION=0.03
    - CLIENT_ID=9160
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities:
            - gpu
    ipc: host
    networks:
    - fl-network
  client_5746:
    image: fl-simulation-img
    runtime: nvidia
    container_name: fl_client_5746
    volumes:
    - ./etc:/app/etc
    depends_on:
      fl-server:
        condition: service_started
    command: python app-client.py --mongo_uri "mongodb://fl_mongo:27017/" --loc="austin"
      --data_path "dataset/pecanstreet/15min/austin/train/" --test_path "dataset/pecanstreet/15min/austin/test/"  --host
      fl-server --filter_bs 5746 --epochs 15 --batch_size 128 --num_workers 0
    environment:
    - NVIDIA_VISIBLE_DEVICES=all
    - CUBLAS_WORKSPACE_CONFIG=:4096:8
    - PYTORCH_ALLOC_CONF=expandable_segments:True
    - MALLOC_ARENA_MAX=2
    - OMP_NUM_THREADS=1
    - GPU_FRACTION=0.03
    - CLIENT_ID=5746
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities:
            - gpu
    ipc: host
    networks:
    - fl-network
  client_1642:
    image: fl-simulation-img
    runtime: nvidia
    container_name: fl_client_1642
    volumes:
    - ./etc:/app/etc
    depends_on:
      fl-server:
        condition: service_started
    command: python app-client.py --mongo_uri "mongodb://fl_mongo:27017/" --loc="austin"
      --data_path "dataset/pecanstreet/15min/austin/train/" --test_path "dataset/pecanstreet/15min/austin/test/"  --host
      fl-server --filter_bs 1642 --epochs 15 --batch_size 128 --num_workers 0
    environment:
    - NVIDIA_VISIBLE_DEVICES=all
    - CUBLAS_WORKSPACE_CONFIG=:4096:8
    - PYTORCH_ALLOC_CONF=expandable_segments:True
    - MALLOC_ARENA_MAX=2
    - OMP_NUM_THREADS=1
    - GPU_FRACTION=0.03
    - CLIENT_ID=1642
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities:
            - gpu
    ipc: host
    networks:
    - fl-network
  client_6139:
    image: fl-simulation-img
    runtime: nvidia
    container_name: fl_client_6139
    volumes:
    - ./etc:/app/etc
    depends_on:
      fl-server:
        condition: service_started
    command: python app-client.py --mongo_uri "mongodb://fl_mongo:27017/" --loc="austin"
      --data_path "dataset/pecanstreet/15min/austin/train/" --test_path "dataset/pecanstreet/15min/austin/test/"  --host
      fl-server --filter_bs 6139 --epochs 15 --batch_size 128 --num_workers 0
    environment:
    - NVIDIA_VISIBLE_DEVICES=all
    - CUBLAS_WORKSPACE_CONFIG=:4096:8
    - PYTORCH_ALLOC_CONF=expandable_segments:True
    - MALLOC_ARENA_MAX=2
    - OMP_NUM_THREADS=1
    - GPU_FRACTION=0.03
    - CLIENT_ID=6139
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities:
            - gpu
    ipc: host
    networks:
    - fl-network
  client_2361:
    image: fl-simulation-img
    runtime: nvidia
    container_name: fl_client_2361
    volumes:
    - ./etc:/app/etc
    depends_on:
      fl-server:
        condition: service_started
    command: python app-client.py --mongo_uri "mongodb://fl_mongo:27017/" --loc="austin"
      --data_path "dataset/pecanstreet/15min/austin/train/" --test_path "dataset/pecanstreet/15min/austin/test/"  --host
      fl-server --filter_bs 2361 --epochs 15 --batch_size 128 --num_workers 0
    environment:
    - NVIDIA_VISIBLE_DEVICES=all
    - CUBLAS_WORKSPACE_CONFIG=:4096:8
    - PYTORCH_ALLOC_CONF=expandable_segments:True
    - MALLOC_ARENA_MAX=2
    - OMP_NUM_THREADS=1
    - GPU_FRACTION=0.03
    - CLIENT_ID=2361
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities:
            - gpu
    ipc: host
    networks:
    - fl-network
  client_3456:
    image: fl-simulation-img
    runtime: nvidia
    container_name: fl_client_3456
    volumes:
    - ./etc:/app/etc
    depends_on:
      fl-server:
        condition: service_started
    command: python app-client.py --mongo_uri "mongodb://fl_mongo:27017/" --loc="austin"
      --data_path "dataset/pecanstreet/15min/austin/train/" --test_path "dataset/pecanstreet/15min/austin/test/"  --host
      fl-server --filter_bs 3456 --epochs 15 --batch_size 128 --num_workers 0
    environment:
    - NVIDIA_VISIBLE_DEVICES=all
    - CUBLAS_WORKSPACE_CONFIG=:4096:8
    - PYTORCH_ALLOC_CONF=expandable_segments:True
    - MALLOC_ARENA_MAX=2
    - OMP_NUM_THREADS=1
    - GPU_FRACTION=0.03
    - CLIENT_ID=3456
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities:
            - gpu
    ipc: host
    networks:
    - fl-network
  client_9019:
    image: fl-simulation-img
    runtime: nvidia
    container_name: fl_client_9019
    volumes:
    - ./etc:/app/etc
    depends_on:
      fl-server:
        condition: service_started
    command: python app-client.py --mongo_uri "mongodb://fl_mongo:27017/" --loc="austin"
      --data_path "dataset/pecanstreet/15min/austin/train/" --test_path "dataset/pecanstreet/15min/austin/test/"  --host
      fl-server --filter_bs 9019 --epochs 15 --batch_size 128 --num_workers 0
    environment:
    - NVIDIA_VISIBLE_DEVICES=all
    - CUBLAS_WORKSPACE_CONFIG=:4096:8
    - PYTORCH_ALLOC_CONF=expandable_segments:True
    - MALLOC_ARENA_MAX=2
    - OMP_NUM_THREADS=1
    - GPU_FRACTION=0.03
    - CLIENT_ID=9019
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities:
            - gpu
    ipc: host
    networks:
    - fl-network
  client_661:
    image: fl-simulation-img
    runtime: nvidia
    container_name: fl_client_661
    volumes:
    - ./etc:/app/etc
    depends_on:
      fl-server:
        condition: service_started
    command: python app-client.py --mongo_uri "mongodb://fl_mongo:27017/" --loc="austin"
      --data_path "dataset/pecanstreet/15min/austin/train/" --test_path "dataset/pecanstreet/15min/austin/test/"  --host
      fl-server --filter_bs 661 --epochs 15 --batch_size 128 --num_workers 0
    environment:
    - NVIDIA_VISIBLE_DEVICES=all
    - CUBLAS_WORKSPACE_CONFIG=:4096:8
    - PYTORCH_ALLOC_CONF=expandable_segments:True
    - MALLOC_ARENA_MAX=2
    - OMP_NUM_THREADS=1
    - GPU_FRACTION=0.03
    - CLIENT_ID=661
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities:
            - gpu
    ipc: host
    networks:
    - fl-network
  client_2818:
    image: fl-simulation-img
    runtime: nvidia
    container_name: fl_client_2818
    volumes:
    - ./etc:/app/etc
    depends_on:
      fl-server:
        condition: service_started
    command: python app-client.py --mongo_uri "mongodb://fl_mongo:27017/" --loc="austin"
      --data_path "dataset/pecanstreet/15min/austin/train/" --test_path "dataset/pecanstreet/15min/austin/test/"  --host
      fl-server --filter_bs 2818 --epochs 15 --batch_size 128 --num_workers 0
    environment:
    - NVIDIA_VISIBLE_DEVICES=all
    - CUBLAS_WORKSPACE_CONFIG=:4096:8
    - PYTORCH_ALLOC_CONF=expandable_segments:True
    - MALLOC_ARENA_MAX=2
    - OMP_NUM_THREADS=1
    - GPU_FRACTION=0.03
    - CLIENT_ID=2818
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities:
            - gpu
    ipc: host
    networks:
    - fl-network
  client_7800:
    image: fl-simulation-img
    runtime: nvidia
    container_name: fl_client_7800
    volumes:
    - ./etc:/app/etc
    depends_on:
      fl-server:
        condition: service_started
    command: python app-client.py --mongo_uri "mongodb://fl_mongo:27017/" --loc="austin"
      --data_path "dataset/pecanstreet/15min/austin/train/" --test_path "dataset/pecanstreet/15min/austin/test/"  --host
      fl-server --filter_bs 7800 --epochs 15 --batch_size 128 --num_workers 0
    environment:
    - NVIDIA_VISIBLE_DEVICES=all
    - CUBLAS_WORKSPACE_CONFIG=:4096:8
    - PYTORCH_ALLOC_CONF=expandable_segments:True
    - MALLOC_ARENA_MAX=2
    - OMP_NUM_THREADS=1
    - GPU_FRACTION=0.03
    - CLIENT_ID=7800
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities:
            - gpu
    ipc: host
    networks:
    - fl-network
  client_7536:
    image: fl-simulation-img
    runtime: nvidia
    container_name: fl_client_7536
    volumes:
    - ./etc:/app/etc
    depends_on:
      fl-server:
        condition: service_started
    command: python app-client.py --mongo_uri "mongodb://fl_mongo:27017/" --loc="austin"
      --data_path "dataset/pecanstreet/15min/austin/train/" --test_path "dataset/pecanstreet/15min/austin/test/"  --host
      fl-server --filter_bs 7536 --epochs 15 --batch_size 128 --num_workers 0
    environment:
    - NVIDIA_VISIBLE_DEVICES=all
    - CUBLAS_WORKSPACE_CONFIG=:4096:8
    - PYTORCH_ALLOC_CONF=expandable_segments:True
    - MALLOC_ARENA_MAX=2
    - OMP_NUM_THREADS=1
    - GPU_FRACTION=0.03
    - CLIENT_ID=7536
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities:
            - gpu
    ipc: host
    networks:
    - fl-network
  client_4767:
    image: fl-simulation-img
    runtime: nvidia
    container_name: fl_client_4767
    volumes:
    - ./etc:/app/etc
    depends_on:
      fl-server:
        condition: service_started
    command: python app-client.py --mongo_uri "mongodb://fl_mongo:27017/" --loc="austin"
      --data_path "dataset/pecanstreet/15min/austin/train/" --test_path "dataset/pecanstreet/15min/austin/test/"  --host
      fl-server --filter_bs 4767 --epochs 15 --batch_size 128 --num_workers 0
    environment:
    - NVIDIA_VISIBLE_DEVICES=all
    - CUBLAS_WORKSPACE_CONFIG=:4096:8
    - PYTORCH_ALLOC_CONF=expandable_segments:True
    - MALLOC_ARENA_MAX=2
    - OMP_NUM_THREADS=1
    - GPU_FRACTION=0.03
    - CLIENT_ID=4767
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities:
            - gpu
    ipc: host
    networks:
    - fl-network
  client_8565:
    image: fl-simulation-img
    runtime: nvidia
    container_name: fl_client_8565
    volumes:
    - ./etc:/app/etc
    depends_on:
      fl-server:
        condition: service_started
    command: python app-client.py --mongo_uri "mongodb://fl_mongo:27017/" --loc="austin"
      --data_path "dataset/pecanstreet/15min/austin/train/" --test_path "dataset/pecanstreet/15min/austin/test/"  --host
      fl-server --filter_bs 8565 --epochs 15 --batch_size 128 --num_workers 0
    environment:
    - NVIDIA_VISIBLE_DEVICES=all
    - CUBLAS_WORKSPACE_CONFIG=:4096:8
    - PYTORCH_ALLOC_CONF=expandable_segments:True
    - MALLOC_ARENA_MAX=2
    - OMP_NUM_THREADS=1
    - GPU_FRACTION=0.03
    - CLIENT_ID=8565
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities:
            - gpu
    ipc: host
    networks:
    - fl-network
  client_4373:
    image: fl-simulation-img
    runtime: nvidia
    container_name: fl_client_4373
    volumes:
    - ./etc:/app/etc
    depends_on:
      fl-server:
        condition: service_started
    command: python app-client.py --mongo_uri "mongodb://fl_mongo:27017/" --loc="austin"
      --data_path "dataset/pecanstreet/15min/austin/train/" --test_path "dataset/pecanstreet/15min/austin/test/"  --host
      fl-server --filter_bs 4373 --epochs 15 --batch_size 128 --num_workers 0
    environment:
    - NVIDIA_VISIBLE_DEVICES=all
    - CUBLAS_WORKSPACE_CONFIG=:4096:8
    - PYTORCH_ALLOC_CONF=expandable_segments:True
    - MALLOC_ARENA_MAX=2
    - OMP_NUM_THREADS=1
    - GPU_FRACTION=0.03
    - CLIENT_ID=4373
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities:
            - gpu
    ipc: host
    networks:
    - fl-network
  client_7901:
    image: fl-simulation-img
    runtime: nvidia
    container_name: fl_client_7901
    volumes:
    - ./etc:/app/etc
    depends_on:
      fl-server:
        condition: service_started
    command: python app-client.py --mongo_uri "mongodb://fl_mongo:27017/" --loc="austin"
      --data_path "dataset/pecanstreet/15min/austin/train/" --test_path "dataset/pecanstreet/15min/austin/test/"  --host
      fl-server --filter_bs 7901 --epochs 15 --batch_size 128 --num_workers 0
    environment:
    - NVIDIA_VISIBLE_DEVICES=all
    - CUBLAS_WORKSPACE_CONFIG=:4096:8
    - PYTORCH_ALLOC_CONF=expandable_segments:True
    - MALLOC_ARENA_MAX=2
    - OMP_NUM_THREADS=1
    - GPU_FRACTION=0.03
    - CLIENT_ID=7901
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities:
            - gpu
    ipc: host
    networks:
    - fl-network
  client_7719:
    image: fl-simulation-img
    runtime: nvidia
    container_name: fl_client_7719
    volumes:
    - ./etc:/app/etc
    depends_on:
      fl-server:
        condition: service_started
    command: python app-client.py --mongo_uri "mongodb://fl_mongo:27017/" --loc="austin"
      --data_path "dataset/pecanstreet/15min/austin/train/" --test_path "dataset/pecanstreet/15min/austin/test/"  --host
      fl-server --filter_bs 7719 --epochs 15 --batch_size 128 --num_workers 0
    environment:
    - NVIDIA_VISIBLE_DEVICES=all
    - CUBLAS_WORKSPACE_CONFIG=:4096:8
    - PYTORCH_ALLOC_CONF=expandable_segments:True
    - MALLOC_ARENA_MAX=2
    - OMP_NUM_THREADS=1
    - GPU_FRACTION=0.03
    - CLIENT_ID=7719
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities:
            - gpu
    ipc: host
    networks:
    - fl-network
  client_9278:
    image: fl-simulation-img
    runtime: nvidia
    container_name: fl_client_9278
    volumes:
    - ./etc:/app/etc
    depends_on:
      fl-server:
        condition: service_started
    command: python app-client.py --mongo_uri "mongodb://fl_mongo:27017/" --loc="austin"
      --data_path "dataset/pecanstreet/15min/austin/train/" --test_path "dataset/pecanstreet/15min/austin/test/"  --host
      fl-server --filter_bs 9278 --epochs 15 --batch_size 128 --num_workers 0
    environment:
    - NVIDIA_VISIBLE_DEVICES=all
    - CUBLAS_WORKSPACE_CONFIG=:4096:8
    - PYTORCH_ALLOC_CONF=expandable_segments:True
    - MALLOC_ARENA_MAX=2
    - OMP_NUM_THREADS=1
    - GPU_FRACTION=0.03
    - CLIENT_ID=9278
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities:
            - gpu
    ipc: host
    networks:
    - fl-network
networks:
  fl-network:
    driver: bridge
    external: true
