services:
  fl-server:
    build: .
    container_name: fl-server
    command: python app-server.py --host 0.0.0.0 --clients_per_round 5 --required_clients ${NUM_CLIENTS} --max_rounds 10
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    ports:
      - "65432:65432"
    healthcheck:
      test: ["CMD", "python", "-c", "import socket; s = socket.socket(); s.connect(('0.0.0.0', 65432))"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True # Alocação dinâmica
    shm_size: '1gb'
    volumes:
      - ./etc/:/app/etc/
    networks:
      - fl-network


  client:
      build: .
      runtime: nvidia
      depends_on:
        fl-server:
          condition: service_healthy
      deploy:
        replicas: ${NUM_CLIENTS}
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: 1
                capabilities: [ gpu ]
      shm_size: '1gb'
      environment:
        - EPOCHS=200
        - LOCALITY=${CURRENT_LOCALITY}
        - FL_SERVER_HOST=fl-server
        - GPU_FRACTION=${GPU_FRAC} # 3% para cada (0.03 * 25 = 0.75 da GPU)
        - NVIDIA_VISIBLE_DEVICES=all
        - CUBLAS_WORKSPACE_CONFIG=:4096:8
        - PYTORCH_ALLOC_CONF=expandable_segments:True

networks:
  fl-network: # Nome corrigido para bater com os serviços
    driver: bridge