services:
  fl-server:
    build: .
    container_name: fl-server
    command: python app-server.py --host 0.0.0.0 --clients_per_round 3 --required_clients 6 --max_rounds 10
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    ports:
      - "65432:65432"
    healthcheck:
      test: ["CMD", "python", "-c", "import socket; s = socket.socket(); s.connect(('0.0.0.0', 65432))"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True # Alocação dinâmica
    shm_size: '1gb'
    volumes:
      - ./etc/:/app/etc/
    networks:
      - fl-network


  client:
      build: .
      runtime: nvidia
      depends_on:
        fl-server:
          condition: service_healthy
      deploy:
        replicas: 25 # Número total de clientes da sua lista
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: 1
                capabilities: [ gpu ]
      shm_size: '1gb'
      environment:
        - FL_SERVER_HOST=fl-server
        - GPU_FRACTION=0.03 # 3% para cada (0.03 * 25 = 0.75 da GPU)
        - NVIDIA_VISIBLE_DEVICES=all
        - CUBLAS_WORKSPACE_CONFIG=:4096:8
        - PYTORCH_ALLOC_CONF=expandable_segments:True
        - CLIENT_ID_LIST=8156 2335 9922 3039 4031 8386 7951 3538 9160 5746 1642 6139 2361 3456 9019 661 2818 7800 7536 4767 8565 4373 7901 7719 9278

networks:
  fl-network: # Nome corrigido para bater com os serviços
    driver: bridge